---
title: "Multi-material distributed recycling via Fused granular fabrication: rHDPE and rPET case of study"

format:
  pdf:
    documentclass: article
    #classoption: [twocolumn, landscape]
    lof: true
    lot: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3, fig.align = 'center', 
  out.width = "100%",
  cache = FALSE,
  echo = FALSE,
  message = FALSE, 
  warning = FALSE,
  fig.show = TRUE,
  hiline = TRUE,
  include = TRUE
)

library(readxl)
library(kableExtra)
library(tidyverse)
library(flextable)
set_flextable_defaults(fonts_ignore=TRUE)
# Link for the Figures
URL = c('https://raw.githubusercontent.com/fabbiocrux/Figures/main/')

```

\section*{Acronyms}

```{r}
read_excel("tables/tables.xlsx", sheet="Acronyms") %>%
   arrange(Acronym) %>% 
   kable(booktabs = T, linesep = "") %>% 
   kable_styling(font_size = 10, full_width = F, position = "left") %>% 
   column_spec(1, bold = T, color = "black")
```



# Introduction
